### PR TITLE
Water-drinking streak

### PR DESCRIPTION
**Pull request by JustAeris**
I added a water-drinking streak system, which can motivate the user to drink assiduously to see his streak go up!
Tell me if an option, per bot or per user, to disable that is necessary.

### CODE REVIEW

**Comment by JustAeris** [comment]
# Please note that system requires further testing

**Review by DelightedCat — APPROVED** [review]

**Comment by JustAeris** [comment]
Added a new command (`wb!waterstreak` or `wbstreak`) to show the current and best streak

**Comment by JustAeris** [comment]
Added a setting in `config.json` to allow bot's owner to enable or disable water-drinking streaks for its users.

**Review by DelightedCat — APPROVED** [review]

**Comment by DelightedCat** [comment]
I just approved the changes. I'll merge it once it's ready!

**Pull request merged**
